# Generated by Django 2.1.3 on 2018-11-19 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('creditos', models.CharField(max_length=200, verbose_name='Creditos')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('direcion', models.CharField(max_length=200, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesors',
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Alumno')),
                ('grados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Grado')),
            ],
            options={
                'verbose_name': 'RegistroAlumno',
                'verbose_name_plural': 'RegistroAlumnos',
            },
        ),
        migrations.CreateModel(
            name='RegistroProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grados', models.ManyToManyField(to='registro.Grado', verbose_name='Grado')),
                ('materias', models.ManyToManyField(to='registro.Materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'RegistroProfesor',
                'verbose_name_plural': 'RegistroProfesors',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['-nombre'],
            },
        ),
        migrations.AddField(
            model_name='grado',
            name='materia',
            field=models.ManyToManyField(related_name='keymateria', to='registro.Materia', verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='grado',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyseccion', to='registro.Seccion'),
        ),
    ]
