# Generated by Django 2.1.3 on 2018-11-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['-nombre'], 'verbose_name': 'Seccion', 'verbose_name_plural': 'Seccions'},
        ),
    ]
